(function(){var k=["comment.verifydata"],g={"comment.reply":"comment.reply.start","comment.postsuccess":"comment.post.success","userinfo.savefromhtml":"userinfo.readFromHtml","comment.posterror":"comment.post.error"},h=function(c,e){if("undefined"===typeof jQuery&&"undefined"===typeof e)throw Error("No jQuery!");this.$=e||window.jQuery;Object.keys||(Object.keys=function(b){return a.$.map(b,function(a,b){return b})});console||(window.console={},console.logs=[],console.log=console.error=console.warning=
function(){console.logs.push(arguments)});k=k.concat(Object.keys(g));var a=this;l(this);c=c||{};c.cookiepath=c.cookiepath||"/";c.bloghost=c.bloghost||location.origin;c.ajaxurl=c.ajaxurl||location.origin;c.commentmaxlength=c.commentmaxlength||1E3;c.lang=c.lang||{};this.eachOnCommentInputs=function(b){return a.$.each(c.comment.inputs,b)};this.eachOnCommentInputs(function(b,d){!d.getter&&d.selector&&(d.getter=function(){return a.$(d.selector).val()});!d.setter&&d.selector&&(d.setter=function(b){return a.$(d.selector).val(b)});
d.validator||(d.validator=function(b,c){for(b=b||d.getter();!(d.required&&""===b.trim()||d.validateRule&&(d.validateRule.lastIndex=0,!d.validateRule.test(b)));)return c(null);return c({code:d.validateFailedErrorCode,message:d.validateFailedMessage||a.options.lang.error[d.validateFailedErrorCode]})})});this.options=c;this.plugin.on("userinfo.output","system",function(){a.eachOnCommentInputs(function(b,d){d.saveLocally&&d.setter(a.userinfo[b])})});this.plugin.on("userinfo.readFromHtml","system",function(){a.eachOnCommentInputs(function(b,
d){d.saveLocally&&(a.userinfo[b]=d.getter())});a.userinfo.save()});this.plugin.on("userinfo.save","system",function(){a.eachOnCommentInputs(function(b,d){d.saveLocally&&(a.userinfo[b]=d.getter(),a.cookie.set("zbp_userinfo_"+b,a.userinfo[b]))})});this.plugin.on("comment.get","system",function(b,d){a.$.get(a.options.bloghost+"zb_system/cmd.php?act=getcmt&postid="+b+"&page="+d,function(c,e,f){a.plugin.emit("comment.got",[b,d],c,e,f)})});this.plugin.on("comment.post.validate","system",function(b){var d=
0,c=!1,e=function(e){c||(e?(c=!0,a.plugin.emit("comment.post.validate.error",e,b)):(d++,d===Object.keys(a.options.comment.inputs).length&&(e={no:0,msg:""},a.plugin.emit("comment.verifydata",e,b),0<e.no?a.plugin.emit("comment.post.validate.error",{number:e.no,message:e.msg},b):a.plugin.emit("comment.post.validate.success",b))))};a.eachOnCommentInputs(function(a,d){d.validator(b[a],e)})});this.plugin.on("comment.post.start","system",function(b){a.eachOnCommentInputs(function(a,c){b[a]=b[a]||c.getter()});
b.commentKey=(new Date).getTime()+""+Math.random();a.plugin.emit("comment.post.validate",b)});this.plugin.on("comment.post.validate.error","system",function(b,d){alert(b.message);console.error(d);console.error("ERROR - "+b.message);a.plugin.emit("comment.post.error",b,d)});this.plugin.on("comment.post.validate.success","system",function(b){a.$.post(b.action,b).done(function(d,c,e){a.plugin.emit("comment.post.success",b,d,c,e)}).fail(function(d,c){a.plugin.emit("comment.post.error",b,{jqXHR:d,message:c,
code:255})})});this.options.comment.useDefaultEvents&&(this.plugin.on("comment.reply.start","system-default",function(b){var d=this;a.$("#inpRevID").val(b);a.$("#cancel-reply").show().bind("click",function(){d.$("#inpRevID").val(0);d.$(this).hide();window.location.hash="#comment";return!1});window.location.hash="#comment"}),this.plugin.on("comment.got","system-default",function(b,d,c,e){a.$("#AjaxCommentBegin").nextUntil("#AjaxCommentEnd").remove();a.$("#AjaxCommentBegin").after(d)}),this.plugin.on("comment.post.start",
"system-default",function(){var b=a.$("#inpId").parent("form").find(":submit");b.data("orig",b.val()).val("Waiting...").attr("disabled","disabled").addClass("loading")}),this.plugin.on("comment.post.done","system-default",function(b){b=a.$("#inpId").parent("form").find(":submit");b.removeClass("loading").removeAttr("disabled");b.data("orig")&&b.val(b.data("orig"))}),this.plugin.on("comment.post.error","system-default",function(b,d){a.plugin.emit("comment.post.done",b,d)}),this.plugin.on("comment.post.success",
"system-default",function(b,d,c,e){var f=a.$("#inpId").parent("form").find(":submit");f.removeClass("loading").removeAttr("disabled").val(f.data("orig"));f=a.$.parseJSON(d);if(0!==f.err.code)throw alert(f.err.msg),Error("ERROR - "+f.err.msg);"0"===b.replyid.toString()?a.$(f.data.html).insertAfter("#AjaxCommentBegin"):a.$(f.data.html).insertAfter("#AjaxComment"+b.replyid);location.hash="#cmt"+f.data.ID;a.$("#txaArticle").val("");a.userinfo.readFromHtml();a.plugin.emit("comment.post.done",b,null,d,
c,e)}));return this};h.prototype._plugins={};var l=function(c){c.utils={};c.utils.getFromIndex=function(a,b){for(var c=[],e=a;e<b.length;e++)c.push(b[e]);return c};var e=function(){};e.prototype.checkIsInterfaceDeprecated=function(a){return 0<=k.indexOf(a)?(console.error("Interface '"+a+"' is deprecated, please update your plugin or theme!"),!0):!1};e.prototype.bind=e.prototype.on=e.prototype.addListener=function(a,b,d){this.checkIsInterfaceDeprecated(a)&&g[a]&&(a=g[a]);"undefined"===typeof c._plugins[a]&&
(c._plugins[a]={});c._plugins[a][b]=d;return c};e.prototype.unbind=e.prototype.removeListener=function(a,b){b||(b="");this.checkIsInterfaceDeprecated(a)&&"system"===b&&(b="system-default",g[a]&&(a=g[a]));""===b?c._plugins[a]={}:c._plugins[a]&&(c._plugins[a][b]=null,delete c._plugins[a][b]);return c};e.prototype.emit=function(a){var b=c.utils.getFromIndex(1,arguments),d;for(d in c._plugins[a])setTimeout(function(d){return function(){c._plugins[a][d].apply(c,b)}}(d),0);return c};e.prototype.listenerCount=
function(a){return Object.keys(c._plugins[a])};c.plugin=new e;e=function(){};e.prototype.get=function(a){return(a=document.cookie.match(new RegExp("(^| )"+a+"=([^;]*)(;|$)")))?unescape(a[2]):null};e.prototype.set=function(a,b,d){var e=new Date;d&&e.setTime(e.getTime()+parseInt(864E5*d));document.cookie=a+"="+escape(b)+"; "+(d?"expires="+e.toGMTString()+"; ":"")+"path="+c.options.cookiepath;return c};c.cookie=new e;e=function(){};e.prototype.output=function(){c.plugin.emit("userinfo.output");return c};
e.prototype.save=function(){c.plugin.emit("userinfo.save");return c};e.prototype.saveFromHtml=e.prototype.readFromHtml=function(){c.plugin.emit("userinfo.readFromHtml");return c};c.userinfo=new e;e=function(){};e.prototype.get=function(a,b){c.plugin.emit("comment.get",a,b)};e.prototype.reply=function(a){c.plugin.emit("comment.reply.start",a)};e.prototype.post=function(a){a=a||{};try{c.plugin.emit("comment.post.start",a)}catch(b){console.error(b)}return!1};c.comment=new e};"function"===typeof define&&
define.amd?define("zbp",[],function(){return h}):"function"===typeof define&&define.cmd?define("zbp",[],function(c,e,a){a.exports=h}):"undefined"!==typeof module?module.exports=h:window.ZBP=h})();