(function(){var g=function(b,c){if("undefined"==typeof jQuery&&"undefined"==typeof c)throw Error("No jQuery!");this.$=c||jQuery;h(this);b=b||{};b.cookiepath=b.cookiepath||"/";b.bloghost=b.bloghost||location.origin;b.ajaxurl=b.ajaxurl||location.origin;b.commentmaxlength=b.commentmaxlength||1E3;b.lang=b.lang||{};this.options=b;this.userinfo.username=this.cookie.get("name");this.userinfo.mail=this.cookie.get("email");this.userinfo.homepage=this.cookie.get("homepage");this.plugin.on("userinfo.output",
"system",function(){this.$("#inpName").val(this.userinfo.username);this.$("#inpEmail").val(this.userinfo.mail);this.$("#inpHomePage").val(this.userinfo.homepage)});this.plugin.on("userinfo.savefromhtml","system",function(){this.userinfo.username=this.$("#inpName").val();this.userinfo.mail=this.$("#inpEmail").val();this.userinfo.homepage=this.$("#inpHomePage").val();this.userinfo.save()});this.plugin.on("userinfo.save","system",function(){this.cookie.set("name",this.userinfo.username);this.cookie.set("email",
this.userinfo.mail);this.cookie.set("homepage",this.userinfo.homepage)});this.plugin.on("comment.verifydata","system",function(a,b){var c={name:[!1,72,/^[\.\_A-Za-z0-9\u4e00-\u9fa5]+$/ig],email:[!0,29,/^[\w-]+(\.[\w-]+)*@[\w-]+(\.[\w-]+)+$/ig],content:[!1,46,/./]},d;for(d in c){var e=c[d];if(!e[0]&&""===b[d]||!e[2].test(b[d])&&""!==b[d])return a.no=e[1],a.msg=this.options.lang.error[a.no],a}c=$("#inpId").parent("form").find(":submit");c.data("orig",c.val()).val("Waiting...").attr("disabled","disabled").addClass("loading")});
this.plugin.on("comment.posterror","system",function(a,b){var c=$("#inpId").parent("form").find(":submit");c.removeClass("loading").removeAttr("disabled").val(c.data("orig"))});this.plugin.on("comment.postsuccess","system",function(a,b,c,d){var e=$("#inpId").parent("form").find(":submit");e.removeClass("loading").removeAttr("disabled").val(e.data("orig"));if(0<b.search("faultCode")&&0<b.search("faultString")){e=b.match("<string>.+?</string>")[0].replace("<string>","").replace("</string>","");alert(e);
try{console.log(arguments),console.log("ERROR - "+e)}catch(g){}}else e=b.match(/cmt\d+/),"0"==a.replyid?this.$(b).insertAfter("#AjaxCommentBegin"):this.$(b).insertAfter("#AjaxComment"+a.replyid),location.hash="#"+e,this.$("#txaArticle").val(""),this.userinfo.saveFromHtml()});this.plugin.on("comment.get","system",function(a,b){var c=this;this.$.get(this.options.bloghost+"zb_system/cmd.php?act=getcmt&postid="+a+"&page="+b,function(d,e,g){c.plugin.emit("comment.got",[a,b],d,e,g)})});this.plugin.on("comment.got",
"system",function(a,b,c,d){this.$("#AjaxCommentBegin").nextUntil("#AjaxCommentEnd").remove();this.$("#AjaxCommentBegin").after(b)});this.plugin.on("comment.reply","system",function(a){var b=this;this.$("#inpRevID").val(a);this.$("#cancel-reply").show().bind("click",function(){b.$("#inpRevID").val(0);b.$(this).hide();window.location.hash="#comment";return!1});window.location.hash="#comment"});return this};g.prototype._plugins={};var h=function(b){var c=function(){};c.prototype.bind=c.prototype.on=
c.prototype.addListener=function(a,c,f){"undefined"==typeof b._plugins[a]&&(b._plugins[a]={});b._plugins[a][c]=f;return b};c.prototype.unbind=c.prototype.removeListener=function(a,c){c||(c="");""===c?b._plugins[a]={}:(b._plugins[a][c]=null,delete b._plugins[a][c]);return b};c.prototype.emit=function(a){for(var c=[],f=1;f<arguments.length;f++)c.push(arguments[f]);for(var d in b._plugins[a])b._plugins[a][d].apply(b,c);return b};b.plugin=new c;c=function(){};c.prototype.get=function(a){return(a=document.cookie.match(new RegExp("(^| )"+
a+"=([^;]*)(;|$)")))?unescape(a[2]):null};c.prototype.set=function(a,c,f){var d=new Date;f&&d.setTime(d.getTime()+parseInt(864E5*f));document.cookie=a+"="+escape(c)+"; "+(f?"expires="+d.toGMTString()+"; ":"")+"path="+b.options.cookiepath;return b};b.cookie=new c;c=function(){};c.prototype.output=function(){b.plugin.emit("userinfo.output");return b};c.prototype.save=function(){b.plugin.emit("userinfo.save");return b};c.prototype.saveFromHtml=function(){b.plugin.emit("userinfo.savefromhtml");return b};
b.userinfo=new c;c=function(){};c.prototype.get=function(a,c){b.plugin.emit("comment.get",a,c);return b};c.prototype.reply=function(a){b.plugin.emit("comment.reply",a);return b};c.prototype.post=function(a){a=a||{};a.action=a.action||$("#inpId").parent("form").attr("action");a.postid=a.postid||$("#inpId").val();a.verify=a.verify||$("#inpVerify").val();a.name=a.name||$("#inpName").val();a.email=a.email||$("#inpEmail").val();a.content=a.content||$("#txaArticle").val();a.homepage=a.homepage||$("#inpHomePage").val();
a.replyid=a.replyid||$("#inpRevID").val();a.isajax=a.isajax||!0;/^(.+)\:\/\//.test(a.homepage)||""==a.homepage||($("#inpHomePage").val("http://"+a.homepage),a.homepage="http://"+a.homepage);var c={no:0,msg:""};b.plugin.emit("comment.verifydata",c,a);if(0!==c.no){alert(c.msg);try{console.log(a),console.log("ERROR - "+c.msg)}catch(f){}b.plugin.emit("comment.posterror",c,a);return!1}b.$.post(a.action,a,function(c,e,f){b.plugin.emit("comment.postsuccess",a,c,e,f)});return b};b.comment=new c};"function"===
typeof define&&define.amd?define("zbp",[],function(){return g}):"function"===typeof define&&define.cmd?define("zbp",[],function(b,c,a){a.exports=g}):window.ZBP=g})();
