<?php
//<language>English</language>
//The second line of this file is the name of the language
//Author:Yang Yixuan
//Author URI:http://www.yangyixuan.com
//E-mail:sen@yangyixuan.com
//Date:20150125

//Custom Information
//Don't delete %s and ()

return array(
	'language' => 'Language:',
	'next' => 'Next',
	'exit' => 'Exit',
	'install_program' => 'Installer',
	'install_progress' => 'Progress:',
	'install_license' => 'Installer License',
	'license_title' => 'Z-BlogPHP End-User License Agreement',
	'install_tips' => 'Installation Notes',
	'install_disable' => 'By examining the configuration file, you have already installed and configured Z-BlogPHP, Setup cannot be used again.',
	'environment_check' => 'Check Server Environment',
	'db_build_set' => 'Database Creation and Setup',
	'install_result' => 'Install Complete',
	'i_agree' => 'I have read and agree to this agreement.',
	'server_check'=> 'Check Server Environment',
	'http_server' => 'HTTP Server',
	'path' => 'Path',
	'php_version' => 'PHP Version',
	'lib_check' => 'Check Component Supports',
	'permission_check' => 'Suthorization Check',
	'function_check' => 'Check function',
	'connect_appcenter' => 'For Connecting App Store',
	'whois_dns' => 'For Parsing DNS',
	'server' => 'Database Host:',
	'database' => 'Database Type:',
	'username' => 'DB Username:',
	'password' => 'DB Password:',
	'db_name' => 'Database Name:',
	'db_pre' => 'Database Prefix:',
	'db_engine' => 'Storage Engine:',
	'db_drive' => 'Database Driver:',
	'db_set_port' => '(Default database port 3306. If you need to change this database port, please follow the example:"Database Host:Database Prefix".)',
	'website_setting' => 'Site Settings',
	'username_intro' => "(Don't worry, you can change it later.)",
	'password_intro' => '(8 characters or more!)',
	'create_db' => 'Created database.',
	'create_table' => 'Connected to this database and created database tables.',
	'exist_table_in_db' => 'Related database tables and datas already exists in this database, please change database prefix, or clear this database before installing.',
	'ok' => 'Finish',
	'index' => 'Home',
	'guestbook' => 'Guestbook',
	'wellcome' => 'Hello, welcome to visit my site!',
	'hello_zblog' => 'Welcome to using Z-BlogPHP!',
	'hello_zblog_content' => '<p>Welcome to using Z-BlogPHP. This post is automatically generated, you can edit or delete it.</p><p>Z-BlogPHP system generated this post and a &quotGuestbook&quot; page. Wish you a pleasant using.</p>',
	'guestbook_content' => 'This guestbook is automatically generated by Z-BlogPHP System. You can edit this page.',
	'create_datainfo' => 'Created and Inserted Data.',
	'save_option' => 'Saved site settings and compiled templates.',
	'dbserver_need' => 'Need to fill in database server.',
	'dbname_need' => 'Need to fill in database name.',
	'dbusername_need' => 'Need to fill in database username.',
	'sitetitle_need' => 'Need to fill in site title.',
	'adminusername_need' => 'Need to fill in administrator username.',
	'adminpassword_need' => 'Need to fill in administrator password.',
	'admin_username' => 'Username:',
	'admin_password' => 'Password:',
	're_password' => 'Re-password:',
	'blog_name' => 'Site Title:',
	'uncategorized' => 'uncategorized',
	'' => '',
);

?>